### ISSUE TITLE
使用 issue-game 在 Issue 上玩游戏！

### ISSUE THREAD

**Issue by xiaohuohumax** [xiaohuohumax/MiaoJi#14]
### 介绍

`issue-game` 是一个这是一个可以在 GitHub Issue 上玩游戏的 Action 项目。

项目地址：[issue-game](https://github.com/xiaohuohumax/issue-game) ，点击开玩：[井字棋](https://github.com/xiaohuohumax/issue-game/issues/new?title=Play%20Tic-Tac-Toe&body=请不要修改%20Issue%20标题和内容，直接提交即可。%0Alanguage:zh '点击此处创建房间，开始游戏')

#### 1. 首先在项目下创建文件 `.github/workflows/issue-game.yaml`

[action详细配置](https://github.com/xiaohuohumax/issue-game?tab=readme-ov-file#-parameters)

```yaml
name: Issue Game

on:
  issues:
    types:
      - opened
  issue_comment:
    types:
      - created

jobs:
  issue-game:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Issue Game Action
        // 若是想使用最新版本，则使用 @v1 => @main
        // 其他版本自行筛选：@vx.x.x
        uses: xiaohuohumax/issue-game@v1
```

#### 2. 设置相关权限

给予 action 读写 Issue 和 Label 的权限，Settings => Actions => General。

#### 3. 游玩

创建一个 Title 为 `Play Tic-Tac-Toe` 的新 Issue。然后稍等片刻，这个 Issue 下就会出现有游戏房间链接的回复，点击加入即可。

### 最后

玩的开心 🎉🎉🎉
