### ISSUE TITLE
利用 changeset + pnpm monorepo + Github action 实现自动发包以及版本管理

### ISSUE THREAD

**Issue by xiaohuohumax** [xiaohuohumax/MiaoJi#17]
**下面将介绍如何通过 pnpm monorepo + changeset + github action 自动发布 npm 包以及版本管理。**

## 配置 pnpm monorepo 环境

pnpm-workspace.yaml

```yaml
packages:
  - packages/**
  - examples/*
```

### 安装依赖

```shell
pnpm add @changesets/cli @changesets/changelog-github -Dw
```

### 初始化

```shell
pnpm changeset init
```

### 修改配置

.changeset/config.json

```json
{
  "$schema": "https://unpkg.com/@changesets/config@1.6.1/schema.json",
  "changelog": [
    "@changesets/changelog-github",
    {
      "repo": "xiaohuohumax/[peoject-name]"
    }
  ],
  "commit": false,
  "linked": [],
  "access": "public",
  "updateInternalDependencies": "patch",
  "ignore": [],
  "baseBranch": "main",
  "___experimentalUnsafeOptions_WILL_CHANGE_IN_PATCH": {
    "updateInternalDependents": "always"
  }
}
```

## 配置 github action

.github/workflows/release-publish.yaml

```yaml
name: Release Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: "chore: :rewind: release version"
          title: "chore: release version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
```

## 配置 package.json

```json
{
  "scripts": {
    "build": "build project command",
    "changeset": "changeset",
    "release": "pnpm build && changeset publish"
  }
}
```

## 配置 github action 权限

Settings => Actions => General

+ Workflow permissions（勾选 Read and write permissions）
+ 勾选 Allow GitHub Actions to create and approve pull requests
+ 保存配置

![Action settings](https://github.com/user-attachments/assets/d44882d4-3a5d-4714-a446-27e0285679b1)

### npm 生成发包令牌

头像 => Access Tokens => Generate New Token => Classic Token

+ 填写令牌名称
+ 选择 Automation 适用于 CICD 可以跳过 2FA 验证
+ 点击生成令牌，之后拷贝令牌到本地暂存供后续使用

![Access Tokens](https://github.com/user-attachments/assets/9b8330bb-32fb-4f64-b58a-4748ede92740)

![Generate New Token](https://github.com/user-attachments/assets/110dfe9f-fc8f-4459-892b-13df8bbb45b0)

![New Classic Token](https://github.com/user-attachments/assets/dd6f9ecc-02f0-4c27-800b-b8f3a5af5e3d)

### 项目添加 npm 令牌

Settings => Secrets and variables =>Actions => Repository secrets => New repository secret

+ 填写 Secret 名称 NPM_PUBLISH_TOKEN
+ 内容则填写刚刚保存的 npm 发包令牌

![Secrets and variables](https://github.com/user-attachments/assets/98034a6c-2c07-4535-958f-f7b0a549b8fc)

![New repository secret](https://github.com/user-attachments/assets/1e7a246a-aade-4597-be5c-1a454573510f)

## 使用

使用 changeset 命令创建新的变更集（即创建新版本号）

> [!WARNING]
> 请勿在本地消耗 变更集（pnpm changeset version）这样会导致 action 不会正常发布合并请求以及 release

```shell
pnpm changeset
```

完成后正常提交代码即可，之后 action 触发消耗掉新的变更集并且向仓库发起一个合并请求（新版本），同意后 action 则会再次启动 自动生成 release 以及 发布新版本的 npm 包
