### ISSUE TITLE
为什么我的 Web Component 继承了样式？

### ISSUE THREAD

**Issue by xiaohuohumax** [xiaohuohumax/MiaoJi#20]
## 简介

Web Components 中 Shadow DOM 的一大优点是样式被封装到组件中，使得组件的样式不易受到外部元素的影响，但外部可继承样式仍然会影响 Web 组件。

## 原文链接

[Why is my Web Component inheriting styles?](https://lamplightdev.com/blog/2019/03/26/why-is-my-web-component-inheriting-styles/)

## 可继承样式

可继承样式是指在父元素上定义的样式会被其子元素继承，常见的例如 `color`、`font`、`line-height` 等。这些样式尽管是在 Shadow DOM 中设置，但会对 Shadow DOM 和 Light DOM（插槽内容）均有效。

## 组件内如何阻止继承样式？

如果开发者希望组件不继承父组件的样式，可以在  Shadow DOM 中使用 `all: initial` 来重置所有可继承样式。

```css
:host {
  all: initial;
}
```

## 组件内如何使用外部样式？

如果希望从外部设置组件样式，可以利用CSS自定义属性以及新的 `::part` 和 `::theme` 伪元素，后续会详细讨论这些内容。

外部设置自定义变量

```css
:root {
  --color: black;
}
```

组件内使用变量

```css
p {
  color: var(--color);
}
```
